### PR TITLE
Fixed Date Range Issues

### LINKED ISSUE #24: Date Range Issues
So, when the start date and the end date are the same day, no results show up, because it's searching 2020-06-12T00:00:00 through 2020-06-12T00:00:00

Maybe the end date time should be 25:59:59

### PR DESCRIPTION
**Pull request by lkellar**
Fixes #24
- Changed timezone in config to America/Chicago, instead of UTC (dont know why it was set that initially)
- Added 00:00:00 to start and 23:59:59 to end. So choosing the same date returns correct results
- Added graceful failure to invalid date. Returns a 400 instead of a 500

### CODE REVIEW

**Comment by jpsank** [comment]
NO NO NO NO NO the timezone in config is the database timezone (if you change that, it will break everything). All datetimes are converted to UTC (database timezone) before being entered in the database; and, when dates are read from the database, we convert them from UTC to the user's local time before displaying.
We may want to rethink how we do the date ranges. When we attach a timezone to the date ranges (which start as naive datetimes), we should attach the user's local timezone, instead of using the database timezone. Then, we convert to the database timezone in order to search for calls within the range.

In practical terms, we need to change this:
```
start = convert_naive_utc(datetime.strptime(start, '%Y-%m-%dT%H:%M:%S'), timezone)
end = convert_naive_utc(datetime.strptime(end, '%Y-%m-%dT%H:%M:%S'), timezone)
```
to this, somehow:
```
start = convert_naive_utc(datetime.strptime(start, '%Y-%m-%dT%H:%M:%S'), local_timezone)
end = convert_naive_utc(datetime.strptime(end, '%Y-%m-%dT%H:%M:%S'), local_timezone)
```

I'm working on a commit.

**Comment by lkellar** [comment]
Where is the app.config timezone used to set db timezone?
Because I searched for any references of app.config, and couldn't find any other uses of the timezone part (save for the other fetch route)

**Comment by jpsank** [comment]
It looks like we don't explicitly reference the app.config timezone; instead, we just assume that the database timezone is UTC.
If you look at each of the scrapers, they all use convert_naive_utc to convert datetimes to UTC before entering them into the database.
I have an idea to make this more clear in my commit.

**Comment by lkellar** [comment]
👍 Sounds good. Thanks for clearing that up.
Also, sidenote, my first instinct was to commit this to master, thinking (it's so small, what could be wrong with it). Glad I did this instead lol

**Comment by jpsank** [comment]
It may be too much of a pain to make the date ranges work as expected. The problem lies in the way we do the routing: since we don't provide anything more than the start and end date to the server (in the `fetch_date_range` function), it has no way of knowing the user's local timezone. Instead, it just uses the UTC date range of those dates.
Meaning: if there is a call that happened at 10pm our time on June 19, the database would show the call happened at 3am June 20 (because UTC is 5 hours ahead). So, if we were searching the date range from June 18 - 19, it would not include that call, even though, in our time, it did happen on the 19th.
If we wanted to fix this, we would have to have another parameter on `fetch_date_range` that specifies the local timezone. Then, we could attach the local timezone to the start and end datetimes and convert them to corresponding UTC.
FOR EXAMPLE!.... if we take the previous example of June 18-19, the `start` param would be America/Chicago 0:00 June 18 and the `end` would be America/Chicago 23:59 June 19. After conversion, `start` would be UTC 5:00 June 18 and `end` would be UTC 4:59 June 20. With these new datetimes it would search the database.

**Comment by lkellar** [comment]
In my initial commit though, it assumed America/Chicago time, then converted to UTC, then searched.

What didn't work about that?

**Comment by lkellar** [comment]
I don't think we should worry about the users local time, we should just force America/Chicago

**Comment by jpsank** [comment]
Ahhh okay that should work, I'll put it back. It makes sense to use the timezone that the actual location is in, anyway.

**Review by jpsank — APPROVED** [review]

**Pull request merged**
